-- AmarSheba PostgreSQL schema for Supabase.
-- Run in Supabase Dashboard > SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(190) not null unique,
  phone varchar(30),
  password varchar(255) not null,
  role varchar(20) not null default 'user' check (role in ('user', 'admin')),
  is_verified smallint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title_en varchar(180) not null,
  title_bn varchar(180) not null,
  category varchar(120) not null,
  description_en text not null,
  description_bn text not null,
  required_documents text,
  fee varchar(120),
  processing_time varchar(120),
  created_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  service_id bigint not null references public.services(id) on delete cascade,
  status varchar(20) not null default 'pending' check (status in ('pending', 'processing', 'approved', 'rejected')),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(190) not null,
  phone varchar(30),
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.email_verification_otps (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  email varchar(190) not null,
  otp_hash varchar(64) not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists services_category_idx on public.services(category);
create index if not exists applications_user_id_idx on public.applications(user_id);
create index if not exists applications_service_id_idx on public.applications(service_id);
create index if not exists contacts_email_idx on public.contacts(email);
create index if not exists otp_user_id_idx on public.email_verification_otps(user_id);
